name: Generate Data

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  generate-data:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Scripts/requirements.txt
        python -m ipykernel install --user --name python3
        
    - name: Execute Jupyter notebook
      run: |
        python Scripts/prepare-data.py
        
    - name: Commit and push if changed
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add movies.pkl similarity.pkl
        git commit -m "Update pickle files" || echo "No changes to commit"
        git push
